import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Alert,
  ScrollView,
  SafeAreaView,
} from 'react-native';
import * as Haptics from 'expo-haptics';

const SimpleInvoicePreview = ({ 
  visible, 
  invoiceData, 
  onClose, 
  onSendWhatsApp 
}) => {
  const handleSendWhatsApp = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    Alert.alert(
      'Send Feature Coming Soon',
      'WhatsApp integration will be available in the next update.',
      [{ text: 'OK', style: 'default' }]
    );
  };

  if (!visible || !invoiceData) return null;

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <View style={styles.headerLeft} />
        <Text style={styles.headerTitle}>Invoice Preview</Text>
        <TouchableOpacity
          style={styles.closeButton}
          onPress={onClose}
          activeOpacity={0.7}
        >
          <Text style={styles.closeButtonText}>✕</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} contentContainerStyle={styles.contentContainer}>
        <View style={styles.invoiceCard}>
          <Text style={styles.title}>📄 Invoice</Text>
          
          {/* Store Info */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Store Information</Text>
            <Text style={styles.text}>🏪 {invoiceData.storeName || 'FlowPOS Store'}</Text>
            <Text style={styles.text}>📍 {invoiceData.storeAddress || 'Store Address'}</Text>
            <Text style={styles.text}>📞 {invoiceData.storeContact || '+91 XXXXXXXXXX'}</Text>
            {invoiceData.storeGSTIN && (
              <Text style={styles.text}>🏛️ GSTIN: {invoiceData.storeGSTIN}</Text>
            )}
          </View>

          {/* Invoice Details */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Invoice Details</Text>
            <Text style={styles.text}>📋 Invoice: {invoiceData.invoiceNumber || 'INV-001'}</Text>
            <Text style={styles.text}>📅 Date: {invoiceData.date || new Date().toLocaleDateString()}</Text>
            <Text style={styles.text}>⏰ Time: {invoiceData.time || new Date().toLocaleTimeString()}</Text>
          </View>

          {/* Customer Details */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Customer Details</Text>
            <Text style={styles.text}>👤 Name: {invoiceData.customerName || 'Walk-in Customer'}</Text>
            {invoiceData.phoneNumber && invoiceData.phoneNumber.trim() && (
              <Text style={styles.text}>📞 Phone: +91 {invoiceData.phoneNumber}</Text>
            )}
            {(!invoiceData.phoneNumber || !invoiceData.phoneNumber.trim()) && (
              <Text style={styles.text}>📞 Phone: Not provided</Text>
            )}
          </View>

          {/* Items */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Items Purchased</Text>
            {invoiceData.items && invoiceData.items.length > 0 ? (
              invoiceData.items.map((item, index) => (
                <View key={index} style={styles.itemRow}>
                  <Text style={styles.itemName}>{item.name || 'Item'}</Text>
                  <Text style={styles.itemDetails}>
                    {item.quantity || 0} × ₹{item.price || 0} = ₹{((item.quantity || 0) * (item.price || 0)).toFixed(2)}
                  </Text>
                </View>
              ))
            ) : (
              <Text style={styles.text}>No items found</Text>
            )}
          </View>

          {/* Totals */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Payment Summary</Text>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Subtotal:</Text>
              <Text style={styles.totalValue}>₹{(invoiceData.subtotal || 0).toFixed(2)}</Text>
            </View>
            {(invoiceData.tax || invoiceData.gst) && (
              <View style={styles.totalRow}>
                <Text style={styles.totalLabel}>Tax (GST):</Text>
                <Text style={styles.totalValue}>₹{(invoiceData.tax || invoiceData.gst || 0).toFixed(2)}</Text>
              </View>
            )}
            <View style={[styles.totalRow, styles.grandTotalRow]}>
              <Text style={styles.grandTotalLabel}>Grand Total:</Text>
              <Text style={styles.grandTotalValue}>₹{(invoiceData.grandTotal || invoiceData.total || 0).toFixed(2)}</Text>
            </View>
          </View>

          {/* Thank You */}
          <View style={styles.thankYouSection}>
            <Text style={styles.thankYouText}>🙏 Thank you for your business!</Text>
            <Text style={styles.footerText}>Generated by FlowPOS</Text>
          </View>
        </View>
      </ScrollView>

      {/* Actions */}
      <View style={styles.actionsContainer}>
        <TouchableOpacity
          style={styles.whatsappButton}
          onPress={handleSendWhatsApp}
          activeOpacity={0.8}
        >
          <Text style={styles.whatsappButtonText}>
            📱 Send Invoice via WhatsApp
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 60, // Proper space for status bar
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerLeft: {
    width: 32, // Same width as close button to balance
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1f2937',
    flex: 1,
    textAlign: 'center',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    color: '#6b7280',
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
  },
  invoiceCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2563eb',
    textAlign: 'center',
    marginBottom: 24,
  },
  section: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 12,
  },
  text: {
    fontSize: 14,
    color: '#374151',
    marginBottom: 4,
    lineHeight: 20,
  },
  itemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f9fafb',
  },
  itemName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1f2937',
    flex: 1,
  },
  itemDetails: {
    fontSize: 14,
    color: '#6b7280',
    textAlign: 'right',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  totalLabel: {
    fontSize: 14,
    color: '#374151',
  },
  totalValue: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1f2937',
  },
  grandTotalRow: {
    borderTopWidth: 2,
    borderTopColor: '#2563eb',
    paddingTop: 8,
    marginTop: 8,
  },
  grandTotalLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2563eb',
  },
  grandTotalValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2563eb',
  },
  thankYouSection: {
    alignItems: 'center',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  thankYouText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#10b981',
    marginBottom: 8,
  },
  footerText: {
    fontSize: 12,
    color: '#9ca3af',
  },
  actionsContainer: {
    padding: 20,
    paddingBottom: 40, // Extra space below WhatsApp button
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  whatsappButton: {
    backgroundColor: '#10b981',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  whatsappButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
});

export default SimpleInvoicePreview;